(clip_class_env) raspberry@raspberrypi:~/Documents/clip_classification/Clip_CNN $ python3 predict_vgg16.py 
/home/raspberry/Documents/clip_classification/Clip_CNN/predict_vgg16.py:13: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(output_signal, GPIO.OUT)
2023-12-05 16:50:01.596067: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 9437184 exceeds 10% of free system memory.
2023-12-05 16:50:01.626911: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 9437184 exceeds 10% of free system memory.
2023-12-05 16:50:01.663690: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 9437184 exceeds 10% of free system memory.
2023-12-05 16:50:01.824236: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 9437184 exceeds 10% of free system memory.
2023-12-05 16:50:01.864686: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 9437184 exceeds 10% of free system memory.
Traceback (most recent call last):
  File "/home/raspberry/Documents/clip_classification/Clip_CNN/predict_vgg16.py", line 24, in <module>
    model.load_model()
  File "/home/raspberry/Documents/clip_classification/Clip_CNN/training_model.py", line 23, in load_model
    self.model = load_model('vgg16_clips.keras')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspberry/Documents/clip_classification/clip_class_env/lib/python3.11/site-packages/keras/src/saving/saving_api.py", line 254, in load_model
    return saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspberry/Documents/clip_classification/clip_class_env/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 281, in load_model
    raise e
  File "/home/raspberry/Documents/clip_classification/clip_class_env/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 269, in load_model
    _load_state(
  File "/home/raspberry/Documents/clip_classification/clip_class_env/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 466, in _load_state
    _load_container_state(
  File "/home/raspberry/Documents/clip_classification/clip_class_env/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 534, in _load_container_state
    _load_state(
  File "/home/raspberry/Documents/clip_classification/clip_class_env/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 435, in _load_state
    trackable.load_own_variables(weights_store.get(inner_path))
  File "/home/raspberry/Documents/clip_classification/clip_class_env/lib/python3.11/site-packages/keras/src/engine/base_layer.py", line 3531, in load_own_variables
    raise ValueError(
ValueError: Layer 'block1_conv1' expected 2 variables, but received 0 variables during loading. Expected: ['block1_conv1/kernel:0', 'block1_conv1/bias:0']
